name: On Release Created

on:
    release:
        types: [created]

jobs: 
    release:
        name: Build - ${{ matrix.platform.release_for }}
        strategy:
            matrix:
                platform:
                    - release_for: FreeBSD-x86_64
                      os: ubuntu-20.04
                      target: x86_64-unknown-freebsd
                      bin: aplookup
                      name: aplookup-FreeBSD-x86_64.tar.gz
                      command: build
                    
                    - release_for: Linux-x86_64
                      os: ubuntu-20.04
                      target: x86_64-unknown-linux-gnu
                      bin: aplookup
                      name: aplookup-Linux-x86_64.tar.gz
                      command: build
                                        
                    - release_for: macOS-x86_64
                      os: macOS-latest
                      target: x86_64-apple-darwin
                      bin: aplookup
                      name: aplookup-macOS-x86_64.tar.gz
                      command: build
                    
                    - release_for: macOS-Aarch64
                      os: macOS-latest
                      target: aarch64-apple-darwin
                      bin: aplookup
                      name: aplookup-macOS-Aarch64.tar.gz
                      command: build
        
        runs-on: ${{ matrix.platform.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build binary
              uses: houseabsolute/actions-rust-cross@v0
              with:
                command: ${{ matrix.platform.commmand }}
                target: ${{ matrix.platform.target }}
                args: "--locked --release"
                toolchain: stable
                strip: true
            - name: Publish
              uses: actions/upload-release-asset@v1
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: ./target/${{ matrix.platform.target }}
                asset_name: ${{ matrix.platform.name }}
                asset_content_type: application/gzip
                